<?php

return [
    'machine_status' => [
        1 => 'Draft',
        2 => 'On Process',
        3 => 'Complete',
        4 => 'Hold',
        5 => 'Cancel',
    ],
    'task_status' => [
        1 => 'Draft',
        2 => 'On Process',
        3 => 'Complete',
        4 => 'Hold',
        5 => 'Cancel',
    ],
    'requisition_status' => [
        1 => 'New',
        2 => 'Partial Delivery',
        3 => 'Delivered',
        4 => 'Hold',
        5 => 'Cancel',
    ],
    'production_status' => [
        1 => 'Draft',
        2 => 'On Production',
        3 => 'Complete',
        4 => 'Hold',
        5 => 'Cancel',
    ],
    'invoice_status' => [
        1 => 'Pending',
        2 => 'Complete',
        3 => 'Partial Complete',
        4 => 'Hold',
        5 => 'Cancel',
    ],
    'invoice_transaction_status' => [
        1 => 'Due',
        2 => 'Paid',
        3 => 'Partial Paid',
        4 => 'Reject',
        5 => 'Cancel',
        6 => 'Hold',
    ],
    'head_of_account_type' => [
        1 => 'sales_module',
        2 => 'purchase_module',
        3 => 'purchase_return_module',
        4 => 'sales_return_module',
        5 => 'receiveable',
        6 => 'payable',
        7 => 'opening_balance',
        8 => 'closing_balance',
        9 => 'input_vat',
        10 => 'output_vat',
        11 => 'sale_discount',
        12 => 'purchase_discount',
        13 => 'sale_shipping_charge',
        14 => 'purchase_shipping_charge',
    ],
];
